time_in_period = "13d8h"
query_type="range"

timetables_implem = "utc_day"

nb_of_queries = 100000

nb_concurrent = 2

run_local = false

[data_source]
gtfs_paths = [
    "/home/pascal/roki-demo/data/ter.zip",
    "/home/pascal/roki-demo/data/tgv.zip",
    "/home/pascal/roki-demo/data/intercites.zip",
    "/home/pascal/roki-demo/data/transfers/"
]


[query.range]
criteria="time_and_legs"
# max_nb_of_legs=4
max_journey_duration = "24h"
max_duration_from_requested_datetime = "2d"
max_wait_duration = "18h"
range_duration = "1d"
overnight_fence = { enable="enabled", time_in_day = "03:10:00", timezone = "Europe/Paris"}
