{
 "title": "Roki",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status_code, api) (rate(in_to_out_durations_count[$__rate_interval]))",
     "legendFormat": "{{api}} {{status_code}}"
    }
   ]
  },
  {
   "title": "In to Out durations ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, api, status_code) (rate(in_to_out_durations_bucket[$__rate_interval])))",
     "legendFormat": "95 percentile api {{api}} status {{status_code}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, api, status_code) (rate(in_to_out_durations_bucket[$__rate_interval])))",
     "legendFormat": "50 percentile api {{api}} status {{status_code}}"
    },
    {
     "expr": "sum by(api, status_code) (rate(in_to_out_durations_sum[$__rate_interval])) / sum by(api, status_code) (rate(in_to_out_durations_count[$__rate_interval]))",
     "legendFormat": "average api {{api}} status {{status_code}}"
    }
   ]
  },
  {
   "title": "Solve durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, worker, api) (rate(solve_durations_bucket[$__rate_interval])))",
     "legendFormat": "95 percentile api={{api}} worker={{worker}}"
    },
    {
     "expr": "sum by(worker, api) (rate(solve_durations_sum[$__rate_interval])) / sum by(worker, api) (rate(solve_durations_count[$__rate_interval]))",
     "legendFormat": "average api={{api}} worker={{worker}}"
    }
   ]
  },
  {
   "title": "Wait durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(wait_durations_bucket[$__rate_interval])))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(wait_durations_bucket[$__rate_interval])))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "sum(rate(wait_durations_sum[$__rate_interval])) / sum(rate(wait_durations_count[$__rate_interval]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Number of  requests in flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by(api) (max_over_time(requests_in_flight[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Realtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Realtime application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(apply_realtime_durations_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apply realtime duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(apply_realtime_durations_bucket[$__rate_interval])))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "sum(rate(apply_realtime_durations_sum[$__rate_interval])) / sum(rate(apply_realtime_durations_count[$__rate_interval]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Realtime feed retreival",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(feed_retreival_durations_count[$__rate_interval])",
     "legendFormat": "{{feed_type}} {{feed_name}} {{success}}"
    }
   ]
  },
  {
   "title": "Realtime feed retreival duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, feed_name, feed_type, success) (rate(feed_retreival_durations_bucket[$__rate_interval])))",
     "legendFormat": "95 percentile {{feed_type}} {{feed_name}} {{success}}"
    },
    {
     "expr": "sum by(feed_name, feed_type, success) (rate(feed_retreival_durations_sum[$__rate_interval])) / sum by(feed_name, feed_type, success) (rate(feed_retreival_durations_count[$__rate_interval]))",
     "legendFormat": "average {{feed_type}} {{feed_name}} {{success}}"
    }
   ]
  },
  { "title": "Tech requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Tech requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status_code, api) (rate(tech_request_durations_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tech request durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(api, status_code) (rate(tech_request_durations_sum[$__rate_interval])) / sum by(api, status_code) (rate(tech_request_durations_count[$__rate_interval]))",
     "legendFormat": "average {{api}} {{status_code}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, api, status_code) (rate(tech_request_durations_bucket[$__rate_interval])))",
     "legendFormat": "50 percentile {{api}} {{status_code}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, api, status_code) (rate(tech_request_durations_bucket[$__rate_interval])))",
     "legendFormat": "95 percentile {{api}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Tech requests in flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by(api) (max_over_time(tech_requests_in_flight[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}